name: Checkov IaC Scan with HTML Report

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  checkov:
    name: Checkov Terraform Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov and generate JSON report
        run: |
          checkov -d . --output json --soft-fail > checkov-report.json

      - name: Convert Checkov JSON report to HTML
        run: |
          python3 <<EOF
          import json
          from pathlib import Path

          with open("checkov-report.json") as f:
              results = json.load(f)

          html = "<html><head><meta charset='UTF-8'><style>body{font-family:Arial}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ccc;padding:8px}th{background:#eee}</style></head><body>"
          html += "<h1>Checkov IaC Report</h1>"

          if isinstance(results, dict) and "results" in results and "failed_checks" in results["results"]:
              checks = results["results"]["failed_checks"]
              if checks:
                  html += "<table><tr><th>ID</th><th>File</th><th>Resource</th><th>Severity</th><th>Message</th></tr>"
                  for check in checks:
                      html += f"<tr><td>{check.get('check_id', '')}</td><td>{check.get('file_path', '')}</td><td>{check.get('resource', '')}</td><td>{check.get('severity', '')}</td><td>{check.get('check_name', '')}</td></tr>"
                  html += "</table><br>"
              else:
                  html += "<p style='color:green'><strong>✅ No failed checks detected.</strong></p>"
          else:
              html += "<p style='color:orange'><strong>⚠️ No data found or unexpected format.</strong></p>"

          html += "</body></html>"
          Path("checkov-report.html").write_text(html)
          EOF

      - name: Upload Checkov JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-json-report
          path: checkov-report.json

      - name: Upload Checkov HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-html-report
          path: checkov-report.html
