name: Secret Detection - Gitleaks

on:
  push:
    paths:
      - '**/*.tf'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.env'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.json'
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.env'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.json'
      - '**/*.py'
  workflow_dispatch:

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --report-format json --report-path gitleaks-report.json

      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report-json
          path: gitleaks-report.json
