name: Trivy SCA Scan with Reports

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  trivy-sca:
    name: Trivy Dependency Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          scanners: "vuln"
          vuln-type: "library"
          format: json
          output: trivy-report.json

      - name: Convert JSON to HTML report
        run: |
          pip install trivy-to-html
          trivy-to-html -i trivy-report.json -o trivy-report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-html-report
          path: trivy-report.html

      - name: Upload JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-json-report
          path: trivy-report.json
