name: Trivy SCA Scan with Reports

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  trivy-sca:
    name: Trivy Dependency Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Trivy Text Table Report
      - name: Run Trivy scan (text)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          scanners: "vuln"
          vuln-type: "library"
          format: table
          output: trivy-report.txt

      - name: Upload table report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report-text
          path: trivy-report.txt

      # Trivy SARIF Report for GitHub Security Dashboard
      - name: Run Trivy scan (SARIF)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          scanners: "vuln"
          vuln-type: "library"
          format: sarif
          output: trivy-results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif

